HTApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('movies/top/', views.topMovies, name='topMovies'),
    path('movies/all/', views.allMovies, name='allMovies'),
    path('movies/all/filter/<slug:slug>/', views.allMovies, name='filterMovies'),
    path('movie/detail/<int:pk>/', views.movieDetail, name='movieDetail'),
    path('user/sign-up/', views.signUpPage, name='signUpPage'),
    path('user/login/', views.loginPage, name='loginPage'),
    path('user/logout/', views.logoutUser, name='logoutUser'),
    path('admin/add-genre/', views.addGenre, name='addGenre'),
    path('admin/add-movie/', views.addMovie, name='addMovie'),
]

HTproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HTApp.urls'))
]

HTApp/models.py
from django.db import models
from pytils.translit import slugify


# Create your models here.
class Genre(models.Model):
    genreName = models.CharField("Genre", max_length=255)
    slug = models.SlugField(unique=True, blank=True, editable=False)

    def __str__(self):
        return f"{self.genreName}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.genreName)
        super().save(*args, **kwargs)


class Movie(models.Model):
    movieName = models.CharField("Movie name", max_length=255)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, verbose_name="Genre")
    year = models.IntegerField("Year")
    producer = models.CharField("Producer", max_length=255)
    cover = models.CharField("Link to cover", max_length=500)
    poster = models.CharField("Link to poster", max_length=500)
    isTop = models.BooleanField("Is top", default=True, blank=True, null=True)
    isRecommended = models.BooleanField("Is recommended", default=False, blank=True, null=True)
    description = models.TextField("Description")
    rating = models.FloatField("Rating")
    movieLink = models.CharField("Link to movie (from youtube)", max_length=500)

    def __str__(self):
        return f"{self.movieName}"

HTApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Genre, Movie

class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class AddGenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ('__all__')

class AddMovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('__all__')

HTApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Genre, Movie
from django.db.models import Q
from .forms import AddMovieForm, AddGenreForm, NewUserForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate

# Create your views here.
def homePage(request):
    return render(request, "user/banner.html")

def topMovies(request):
    movie = Movie.objects.all()[:1]
    movies = Movie.objects.all()[:10]
    return render(request, "user/top-movies.html", {
        'movie': movie,
        'movies': movies,
    })

def allMovies(request, slug=None):
    genre = None
    movies = Movie.objects.all()
    genres = Genre.objects.all()
    searchData = request.GET.get('search')
    if searchData:
        movies = Movie.objects.filter(Q(movieName__icontains=searchData) | Q(description__icontains=searchData))
    else:
        movies = Movie.objects.all()
    if slug:
        genre = get_object_or_404(Genre, slug=slug)
        movies = movies.filter(genre=genre)
    return render(request, 'user/all-movies.html', {
        'movies': movies,
        'genres': genres,
        'genre': genre,
    })

def movieDetail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    return render(request, 'user/movie-detail.html', {
        'movie': movie
    })

def addMovie(request):
    if request.method == 'POST':
        form = AddMovieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('allMovies')
    else:
        form = AddMovieForm()

    return render(request, 'admin/add-movie.html', {
        'form': form,
    })

def addGenre(request):
    if request.method == 'POST':
        form = AddGenreForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('allMovies')
    else:
        form = AddGenreForm()

    return render(request, 'admin/add-genre.html', {
        'form': form,
    })

def signUpPage(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('loginPage')
    else:
        form = NewUserForm()
    return render(request, 'auth/sign-up.html', {
        'form': form,
    })

def loginPage(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('topMovies')
    else:
        form = AuthenticationForm()
    return render(request, 'auth/login.html', {
        'form': form
    })

def logoutUser(request):
    logout(request)
    return redirect('homePage')

HTApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static './css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static './css/owl.carousel.min.css' %}">
    <link rel="icon" type="image/x-icon" href="/static/img/SiteIcon.png">
</head>
<style>
label {
display: block;
font-size: 20px;
margin-right: 10px;
}
input, textarea {
width: 100%;
margin: 5px 0;
}
select {
margin: 5px 0;
}
#id_year, #id_producer, #id_rating {
width: fit-content;
}
.btn {
margin-top: 10px;
}
</style>
<body>
<header class="navbar navbar-expand-lg navbar-dark">
    <div class="container mt-2 mb-3">
        <img src="/static/img/logo.png" width="40px" style="margin-right: 10px;">
        <a class="navbar-brand" href="{% url 'homePage' %}">HT</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'homePage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'topMovies' %}">Movies</a>
                </li>
                {% if user.is_authenticated %}
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'addMovie' %}">Add Movie</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'addGenre' %}">Add Genre</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'logoutUser' %}">{{ user.username }}: Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'signUpPage' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'loginPage' %}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>

{% block content %}
{% endblock %}

<script src="{% static './js/jquery.min.js' %}"></script>
<script src="{% static './js/owl.carousel.min.js' %}"></script>
<script src="{% static './js/carousel.js' %}"></script>
<script src="{% static './js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static './js/script.js' %}"></script>
</body>
</html>

HTApp/templates/user/all-movies.html
{% extends '../base.html' %}

{% block title %}All movies{% endblock %}

{% block content %}
    <div class="top-ten">
        <div class="container">
            <h2 class="mt-5 mb-5">All movies</h2>
            <div class="row">
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h3>Search</h3>
                            <form class="mb-4" action="{% url 'allMovies' %}">
                                <div class="row">
                                    <div class="col-9">
                                        <input type="search" name="search" class="form-control" placeholder="Film name, description">
                                    </div>
                                    <div class="col-3">
                                        <button type="submit" class="btn btn-primary m-1">Search</button>
                                    </div>
                                </div>
                            </form>
                            <h3>Genre's</h3>
                            <ul>
                                <li><a href="{% url 'allMovies' %}" class="text-dark">All movies</a></li>
                                {% for genre in genres %}
                                <li><a href="{% url 'filterMovies' slug=genre.slug %}" class="text-dark">{{ genre.genreName }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    {% for movie in movies %}
                    <div class="card mb-4">
                        <div class="card-body" style="display: flex;justify-content:space-between;">
                            <img src="{{ movie.poster }}" width="20%">
                            <h2 style="right:15px;text-align:right;">{{ movie.movieName }}</h2>
                            <a href="{% url 'movieDetail' pk=movie.pk %}" class="btn btn-primary" style="position:absolute;right:15px;bottom:15px;">Watch</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

HTApp/templates/user/banner.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HT</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}">
    <link rel="icon" type="image/x-icon" href="/static/img/SiteIcon.png">
</head>
<body>
<header class="navbar navbar-expand-lg navbar-dark">
    <div class="container mt-2 mb-3">
        <img src="/static/img/logo.png" width="40px" style="margin-right: 10px;">
        <a class="navbar-brand" href="{% url 'homePage' %}">HT</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-ite">
                    <a class="nav-link active" aria-current="page" href="{% url 'homePage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'topMovies' %}">Movies</a>
                </li>
                {% if user.is_authenticated %}
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'addMovie' %}">Add Movie</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'addGenre' %}">Add Genre</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'logoutUser' %}">{{ user.username }}: Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'signUpPage' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'loginPage' %}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>
<div id="banner">
    <div class="container">
        <h1>Looking for something to watch?</h1>
        <p>Come check this site</p>
        <a href="{% url 'allMovies' %}" class="btn btn-primary">All Movies</a>
        <a href="{% url 'signUpPage' %}" class="btn btn-outline-primary">Sign Up</a>
    </div>
</div>
<script src="{% static './js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static './js/script.js' %}"></script>
</body>
</html>

HTApp/templates/user/movie-detail.html
{% extends '../base.html' %}

{% block title %}{{ movie.movieName }}{% endblock %}

{% block content %}
<style>
    body {
        background:linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url({{ movie.cover }});
        background-repeat:no-repeat;
        background-size:cover;
        background-position:center;
    }
</style>
    <div class="container mt-5 mb-5">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <div style="width: 100%;">
                            <img src="{{ movie.poster }}" width="100%">
                        </div>
                    </div>
                    <div class="col-md-8">
                        <h1>{{ movie.movieName }}</h1>
                        <p><b>{{ movie.rating }}</b></p>
                        <p>Year: <b>{{ movie.year }}</b> | Genre: <b>{{ movie.genre.genreName }}</b> | Produced by <b>{{ movie.producer }}</b></p>
                        <p>Description: <i>{{ movie.description }}</i></p>
                        <a href="#movie" class="btn btn-primary">Play</i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="movie" class="container mb-5">
        <div class="card">
            <div class="card-body">
                <iframe width="100%" height="710px" src="{{ movie.movieLink }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>
        </div>
    </div>
{% endblock %}

HTApp/templates/user/top-movies.html
{% extends '../base.html' %}

{% block title %}Top movies{% endblock %}

{% block content %}
<style>
    .owl-nav {
    display:none;
    }
</style>
    <div class="recommended mt-5 mb-5">
        <div class="container">
            {% for m in movie %}
            {% if m.isRecommended %}
            <div class="card">
                <div class="card-body">
                    <h2>{{ m.movieName }}</h2>
                    <h3>Genre: {{ m.genre }}</h3>
                    <p>Description: {{ m.description }}</p>
                    <a href="{% url 'movieDetail' pk=m.pk%}" class="btn btn-primary">Watch</a>
                </div>
            </div>
            {% else %}
            <span></span>
            {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="top-ten">
        <div class="container">
            <h2>Top 10 movies</h2>
            <div class="owl-carousel owl-theme">
                {% for m in movies %}
                {% if m.isTop %}
                <div class="item">
                    <div class="card">
                        <div class="card-body">
                            <h2>{{ m.movieName }}</h2>
                            <a href="{% url 'movieDetail' pk=m.pk%}" class="btn btn-primary">Watch</a>
                        </div>
                    </div>
                </div>
                {% else %}
                <span></span>
                {% endif %}
                {% endfor %}
            </div>

            <div class="mt-5 mb-5 text-center">
                <a href="{% url 'allMovies' %}" class="btn btn-primary">See All</a>
            </div>
        </div>
    </div>
{% endblock %}